### ISSUE TITLE
Spring Security - OAuth2 Client

### ISSUE THREAD

**Issue by kang-jisu** [kang-jisu/spring-security-oauth2-jwt-practice#2]
이전에는 Spring Security의 기본으로 아이디와 비밀번호를 직접 입력해서 회원가입했다면 이번에는 OAuth2를 사용한 로그인을 진행해본다. 
OAuth를 사용하는 이유는 인증된 제 3자 서비스를 이용해서 유저 정보를 제공받고 이를 기반으로 어플리케이션 사용자에게 간편하고 안전한 로그인을 제공하기 위해서이다. 

**Oauth 구성 요소**
- Resource Owner : 사용자 ( 우리가 회원기능을 구현하기 위한 리소스의 실제 주인 )
- Client : 서버 ( 리소스 서버에서 제공해주는 자원을 사용해주는 플랫폼 - 우리가 만든 프로젝트 서버)
- Authoriztion Server : Client가 Resource Owner의 자원을 사용할 수 있도록 인증하고 토큰을 발급해주는 서버
- Resource Server : 사용자의 자원을 제공해주는 서버 ( AccessToken으로 UserInfo를 요청)

**Oauth 동작 방식**
```bash
  +--------+                                           +---------------+
  |        |--(A)------- Authorization Grant --------->|               |
  |        |                                           |               |
  |        |<-(B)----------- Access Token -------------|               |
  |        |               & Refresh Token             |               |
  |        |                                           |               |
  |        |                            +----------+   |               |
  |        |--(C)---- Access Token ---->|          |   |               |
  |        |                            |          |   |               |
  |        |<-(D)- Protected Resource --| Resource |   | Authorization |
  | Client |                            |  Server  |   |     Server    |
  |        |--(E)---- Access Token ---->|          |   |               |
  |        |                            |          |   |               |
  |        |<-(F)- Invalid Token Error -|          |   |               |
  |        |                            +----------+   |               |
  |        |                                           |               |
  |        |--(G)----------- Refresh Token ----------->|               |
  |        |                                           |               |
  |        |<-(H)----------- Access Token -------------|               |
  +--------+           & Optional Refresh Token        +---------------+
```

보통 OAuth의 인증 종류(grant type)으로  Autorization Code을 사용해 개발한다.
1. Resouce Owner로 부터 리소스 사용 동의를 받으면 Authorization Server는 Client에게 Token을 발급해준다.
2. Client는 Token을 가지고 Resource Server의 Resource Owner의 정보를 요청한다. 
3. Client는 받은 정보를 이용해서 로그인을 진행하거나, 추가적인 회원가입으로 어플리케이션에 필요한 기능을 개발한다
4. Access Token이 만료되면 웹페이지를 사용하고 있는 Resource Owner모르게 Authorizaion Server에게 refresh token을 이용해 새로운 accessToken을 발급받고, 2~3을 반복한다. 

이런식으로 oauth를 이용한 로그인이 진행되고 3,4번을 어떻게 구현하느냐에 따라 다르다. 

## 개발 
1. 로그인을 사용할 google, naver, kakao 개발자사이트에서 어플리케이션을 등록하고, client-id 와 client-secret을 발급받고 redirect_uri을 설정한다. (구글 로그인 완료시 인가 code를 받을 uri)
  - kakao는 REST API 키가 client-id이고 secret은 추가적으로 선택하면 사용할 수 있다 -> Secret값은 기본적으로 비어있지만 사용한다고 선택 한 이후에는 secret값이 채워져야함 
  - application.yml 필요한 정보를 채우는데 google, facebook, twitter등 같은 경우에는 spring oauth2-client 라이브러리에서 해당 서비스를 provider로 지정해두어서 자동으로 적용되는게 있는데, Naver나 kakao는 기본제공되는값이 없어서 우리가 추가로 provider 항목을 지정해줘야한다. 
 
```yaml
security:
    oauth2:
      client:
        registration:
          google:
            client-id: xxx
            client-secret: xxx
            scope:
              - email
              - profile
          naver:
            clientId: xxx
            clientSecret: xxx
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - nickname
              - email
              - profile_image
            clientName: Naver
        provider: # google은 기본으로 설정되어있음 
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize # 로그인 폼에서 /oauth2/authorization/naver 주소로 요청보내면 해당 uri로 서비스에게 권한코드 발급 요청을 보냄 
            tokenUri: https://nid.naver.com/oauth2.0/token # 토큰 발급 요청 보내는 uri
            userInfoUri: https://openapi.naver.com/v1/nid/me # 유저 정보 얻어오는 uri 
            userNameAttribute: response #naver 회원 조회시 반환되는 JSON 형태 때문
```

### 의존성 추가
```gradle
implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
```
### loginpage 설정 및 userService 등록 
```java
// SecurityConfig
        http.oauth2Login()
                .loginPage("/login-form") // 로그인 페이지 url을 수동으로 변경해줌 
                .userInfoEndpoint()
                .userService(principalOauth2UserService);// 그리고 구글 로그인이 완료된 후 후처리 필요 -> Tip 구글로그인이 완료되면 코드가 아닌 액세스 토큰 + 사용자 프로필 정보를 한번에 받음 (oauth가 인증정보 받아오는단계까지 다 해줌)
 
```
이걸 설정하지 않으면 security에서 provider 값을 보고 알아서 로그인 페이지를 만들어준다.

---
## 정리

실제 구현이랑 연관지어 생각해보면 세션을 사용할 경우 

**SecurityContextHolder의 `SecurityContext` (security session)에 저장된 `Authentication`객체에 UserDetails 객체를 저장한다.** 우리는 여기 있는 UserDetails를 불러와서 현재 세션에 접속중인 로그인 정보를 확인하는 것이다.   

<br/>

**스프링 시큐리티** 

- 자기만의 시큐리티 세션을 들고 있다. (서버 세션안에 시큐리티가 관리하는 세션이 따로 있음)
- 시큐리티 섹션에는 Authentication 객체만 들어갈수있음 -> 로그인된것
  - Authentication 안에 들어갈 수 있는 타입 2개 
  - UserDetails -> 일반 로그인
  - OAuth2User -> oauth 로그인 

그럼 알아야 할 것은 

- 로그인 요청이 들어오면 어떤 일이 일어나는가
- UserDetails 객체를 어떻게 반환하는가

<br/>

1. 로그인 요청이 들어오면 어떤 일이 일어나는가

UserDetailService 인터페이스를 구현한 클래스에서 `UserDetails`객체를  반환하는 `loadUser` (OAuth) 또는 `loadUserByUsername`(Security) 함수를 오버라이딩 해서  유저 정보를 얻어오는 작업을 거친다.

- Bean 등록
  - `WebSecurityConfigurerAdapter`를 상속받고 `@EnableWebSecurity` 어노테이션을 지정하여 시큐리티 필터체인에 등록한 `SecurityConfig` 파일을 만들어 `.userService(xxxUserService)`로 등록해주면된다. 
- User 정보 얻어오기
  - 기본 Security - DB에 저장해뒀다가 불러온다. 보통 User엔티티는 username과 password 형식을 맞춘다. 
  - OAuth - Authentication Server에게서 token을 얻고 token으로 userinfo를 조회해온다. 
- UserDetails 객체 반환하기 - `service.loadUser~~()`
  - Security - UserDetails
    -  DB에서 얻어온 user 엔티티 정보를 넣어 반환
  - OAuth - OAuth2User 
    - resource server에서 얻은 user info로 값을 채워 반환 
  - 이때 Security와 OAuth를 둘 다 같이 쓴다면, `UserDetails`와 `OAuth2User`를 모두 구현한 `CustomUserDetails`와 같은 클래스를 만들어 getAttributes, getAuthority, getXXX(), 등을 구현하여 사용하면 된다.
- 이 값을 컨트롤러에서 파라미터로 `Authentication` 객체나 `@AuthenticationPrincipal UserDetails userDetails` 와 같은 방식으로 얻어올 수 있다. 
  - Authentication.getPrincipal() == userDetails
